---
title: "Template for goal-setting meetings"
format: pdf
editor: visual
---

## Agenda
1. **Review Previous Goals**
    -   Read 3-4 chapters of *Life of a Leaf*
    -   Finish reading Marshall & Biscoe (1980)
    -   *BSD3* chapters 5 & 6 in particular. Skim background in Chapters 1-4 if desired.
    -   Revise rank and trace plots
    -   Why are leaves green?
        -   Terashima et al. 2011 discusses one hypothesis
        -   ? (CDM will find this paper later)
    -   Summarize $\hat{R}$ and ESS for model parameters
    -   Start writing methods to describe how and why you chose specific dignostic plots (trace plots, rank plots, etc.) and convergence statistics (e.g. ESS) with reference to Vehtari et al. (2021) or other papers.
2. **Current Goals**
    -   Finished reading BDA chapter 6
    -   Finished reading *The Life of a Leaf* chapter 7, 8
    -   Finished reading Oguchi et al. (2018)
    -   Beautify the convergence plot
    -   Second draft of Methods script
    -   Check if there is any possible improvement for the model
3. **Next Steps**
   - Plan actions for the upcoming week.

## Action Items
- [ ] Task 1: ...
- [ ] Task 2: ...
- [ ] Task 3: ...

## Additional Notes
- Remember to track progress and adjust goals as needed.

