---
title: "2024-05-31"
format: pdf
editor: visual
---

## Agenda

1.  **Review Current Goals**
    -   Co-create mentoring agreement
    -   Make sure timesheet works
    -   Get key for Birge 201
    -   Explore data and model code
    -   Start data README
    -   Ask lots of questions
    -   Set up GitHub and Zotero
    -   Start reading *Life of a Leaf*
2.  **Progress Update**
    -   Finished mentoring agreement
    -   Timesheet not worked yet
    -   Got the key for Birge 201
    -   Start to revise the model
    -   Draw the rank plots, quantile & small-interval plots to check if the fitting progress
    -   Github and Zotero are in use
3.  **Challenges and Roadblocks**
    -   Failed to identify a param groups to draw the plot
    -   Confused about why we need to introduce acc_id and acc in the model
4.  **Next Steps**
    -   Solve the problem above
    -   Write R script `XX_plot_convergence.r` to generate graphs automatically after model fitted
    -   Study further about the domain knowledge behind this model
    -   Continue to read *Life of a Leaf*

## Action Items

-   [ ] Task 1: ...
-   [ ] Task 2: ...
-   [ ] Task 3: ...

## Additional Notes

-   Remember to track progress and adjust goals as needed.
