---
title: "2024-07-11 weekly meeting agenda"
format: pdf
editor: visual
---

## Agenda

1.  **Review Current Goals**

    -   Revise the code for generating figures for cmdstanfit objects
    -   Try to find out why there is a chain always not mixed with others
    -   Revise the manuscript to discuss about our strategy to fit this new model
    -   Address old comments on **Model Evaluation** subsection
    -   Address new comments on **Check Outliers** subsection
    -   Address new comments **Posterior Predictive Checking** subsection
    -   Start draft Methods subsection on **Model fitting**
        -   First describe nonphylogenetic model using **brms**
        -   Next, describe phylogenetic model using **cmdstanr**
2.  **Progress Update**

    -   revised the code for generating figures for cmdstanfit object
    -   extracted the posterior distribution of important parameters
    -   made the corresponding stan code with brm/stan models' parameters and one version without convariance matrices
    -   revised the manuscript
3.  **Challenges and Roadblocks**

    -   some unclear distributions for parameters
4.  **Next Steps**
    -   Plan actions for the upcoming week.

## Action Items

-   [ ] Task 1: ...
-   [ ] Task 2: ...
-   [ ] Task 3: ...

## Additional Notes

-   Remember to track progress and adjust goals as needed.
