---
title: "Research Log"
format: html
editor: visual
---

# 2024-05

## 2024-05-28

-   Onboarding
-   Finished *The Life of a Leaf* chapter 1, start reading chapter 2
-   Finished reading code step 1,2,3, read step 4 tomorrow
-   Added some paramters explanation in README file

## 2024-05-29

-   Finished reading code step 4
-   Finished reading the first 3 chapters of Vehtari et al., start reading chapter 4
-   Read *The Life of a leaf* chapter 2

## 2024-05-30

-   Finished reading Vehtari et al.(2021)
-   Start trying to write some code to test the convergence efficiency of the current fitting method

## 2024-05-31

-   Made the trace and rank plot for the model `fit1`
-   Finished reading chapter 2 of *The Life of a Leaf*

# 2024-06

## 2024-06-03

-   Finished reading chapter 3 of *The Life of a Leaf*
-   Started reading chpater 5 of BDA3
-   Start to make the variable name list of the brm model

## 2024-06-04

-   Finished reading chapter 4-5 of *The Life of a Leaf*
-   Finished reading Marshall & Biscoe (1980)

## 2024-06-05

-   Finished reading chapter 6 of *The Life of a Leaf*
-   Finished plotting convergence diagnostic graph, listed Rhat, Bulk_ESS, Tail_ESS of main parameters of the brm model

## 2024-06-06

-   Finished reading chapter 5 of BDA3
-   Finished reading Terashima et al.(2011)

## 2024-06-07

-   Revised XX_check_convergence.R, now with $\hat{R}$, Bulk-ESS, Tail-ESS shown on the plot
-   Started Reading chapter 6 of BDA3

## 2024-06-10

-   Retrieved some extra information for the model *fit1*
-   Finished reading chapter 7 of *The Life of a Leaf*

## 2024-06-11

-   Draft for `check_outliers` function, wait to complete
-   Finished reading chapter 8 of *The Life of a Leaf*

## 2024-06-12

-   Finished `r/XX_check-outliers.R`

## 2024-06-13

-   Finished reading JOSEF C. UYEDA et al.(2018)
-   Revised `r/XX_check-convergence.R` and related figures

## 2024-06-14

-   Revised `r/XX_check-outliers.R` with z-score and pareto_k implementation

## 2024-06-18

-   Reviewed JOSEF C. UYEDA et al.(2018)
-   Finished reading section 14.5.2 of *Statistical Rethinking*

## 2024-06-19

-   Revised the previous methods
-   Written outlines for "Check Outlier" part of methods script
-   Comments for variables in the stan code
-   Draft for `pp_check()` in `r/XX_check-outliers.R`

## 2024-06-21

-   revised `r/03_check-outliers.R` for density plot
-   first edition for the stan code to generate log likelihood
-   first edition for the check outlier part in the method script

## 2024-06-24

-   added mean, sd, 2d figure and quantitative statistics to `r/03_check-outliers.R`
-   added pareto k diagnostic graph
-   slice data
-   tested stan model for the first round

## 2024-06-25

-   Read the paper *Bayesian statistics and modelling*

## 2024-06-26

-   Read the paper *Bayesian statistics and modelling*
-   Test the stan model


## 2024-06-27

-   Reformat the code in `r/03_check-outliers.R` and make new graphs
-   Filter the outlier with studentized residuals and start fit the non phylogenetic model with filtered data
-   Finished reading the paper *Bayesian statistics and modelling*

# 2024-07

## 2024-07-02

-   Train the phylogeny model with filtered pareto k and filtered studentized residual dataset
-   Revise the sd diff figures
-   Revise the manuscript

## 2024-07-03

-   read *Visualization in Bayesian workflow*
-   read about how PIT works

## 2024-07-04

-   make graphs for the model with phylo information, starting with convergence test

## 2024-07-05

-   revise graphs for the model with phylo information
-   assesses why the 3rd chain is deviated from others

## 2024-07-08

-   extract the draws data from brm and stan model chain 1,2,4, and generate figures to show the distribution of these draws
-   Revise the parameter of the stan model

## 2024-07-10

-   Finished revise the paramter of the stan model
-   Revised the manuscript

## 2024-07-11

-   Write the manuscript about fitting model with `brms` and *stan*

## 2024-07-12

-   Write the code to generate a table with parameter overview